[application]
name = "vibe-studio"
default_platform = "web"

[web.app]
title = "Vibe Studio"

[web.resource]
style = ["assets/style.css"]
script = []

[web.resource.dev]
style = []
script = []

[web.resource.prod]
style = []
script = []
