[application]
name = "vibe-studio"
default_platform = "web"

[web.app]
title = "Vibe Studio"
base_path = "/vibestudio/"

[web.resource]
style = ["assets/style.css"]
head = ["<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\">"]
script = []

[web.resource.dev]
style = []
script = []

[web.resource.prod]
style = []
script = []
